package entities;
// Generated Dec 29, 2015 2:35:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Lottery generated by hbm2java
 */
@Entity
@Table(name="lottery"
    ,schema="container"
    , uniqueConstraints = @UniqueConstraint(columnNames={"lotterydate", "lotterytype"}) 
)
public class Lottery  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private int id;
    @Temporal(TemporalType.DATE)
    @Column(name="lotterydate", nullable=false, length=13)
    private Date lotterydate;
    
    @Column(name="lotterytype")
    private Integer lotterytype;

    public Lottery() {
    }

	
    public Lottery(int id, Date lotterydate) {
        this.id = id;
        this.lotterydate = lotterydate;
    }
    public Lottery(int id, Date lotterydate, Integer lotterytype) {
       this.id = id;
       this.lotterydate = lotterydate;
       this.lotterytype = lotterytype;
    }
   
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public Date getLotterydate() {
        return this.lotterydate;
    }
    
    public void setLotterydate(Date lotterydate) {
        this.lotterydate = lotterydate;
    }

    
    public Integer getLotterytype() {
        return this.lotterytype;
    }
    
    public void setLotterytype(Integer lotterytype) {
        this.lotterytype = lotterytype;
    }
  
}


