package entities;
// Generated Dec 29, 2015 2:35:46 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.JoinColumn;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import entities.Lottery;
import java.util.ArrayList;
import javax.persistence.CascadeType;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;

/**
 * Numbers generated by hbm2java
 */
@Entity
@Table(name="numbersmulti"
    ,schema="container"
    , uniqueConstraints = @UniqueConstraint(columnNames="lotteryid") 
)
public class NumbersMulti  implements java.io.Serializable {

    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    private int id;
    @Column(name="numberone", nullable=false)
    private int numberone;
    @Column(name="numbertwo", nullable=false)
    private int numbertwo;
    @Column(name="numberthree", nullable=false)
    private int numberthree;
    @Column(name="numberfour", nullable=false)
    private int numberfour;
    @Column(name="numberfive", nullable=false)
    private int numberfive;
    @Column(name="numbersix", nullable=false)
    private int numbersix;
    
    @Column(name="numberseven", nullable=false)
    private int numberseven;
    
    @Column(name="numbereight", nullable=false)
    private int numbereight;
    
    
    @Column(name="numbernine", nullable=false)
    private int numbernine;
    
    @Column(name="numberten", nullable=false)
    private int numberten;
    
    @Column(name="numbereleven", nullable=false)
    private int numbereleven;
    
    @Column(name="numbertwelve", nullable=false)
    private int numbertwelve;
    
    @Column(name="numberthirteen", nullable=false)
    private int numberthirteen;
    
    @Column(name="numberfourteen", nullable=false)
    private int numberfourteen;
    
    @Column(name="numberfivteen", nullable=false)
    private int numberfivteen;
    
    @Column(name="lotteryid", unique=true)
    private Integer lotteryid;
  
    public NumbersMulti() {}
	
    public NumbersMulti (ArrayList<Integer> numbers) {
        this.numberone = numbers.get(0);
        this.numbertwo = numbers.get(1);
        this.numberthree = numbers.get(2);
        this.numberfour = numbers.get(3);
        this.numberfive = numbers.get(4);
        this.numbersix = numbers.get(5);
        this.numberseven = numbers.get(6);
        this.numbereight = numbers.get(7);
        this.numbernine = numbers.get(8);
        this.numberten = numbers.get(9);
        this.numbereleven = numbers.get(10);
        this.numbertwelve = numbers.get(11);
        this.numberthirteen = numbers.get(12);
        this.numberfourteen = numbers.get(13);
        this.numberfivteen = numbers.get(14);
    }
    
    public NumbersMulti (int id, ArrayList<Integer> numbers) {
        this.id = id;
        this.numberone = numbers.get(0);
        this.numbertwo = numbers.get(1);
        this.numberthree = numbers.get(2);
        this.numberfour = numbers.get(3);
        this.numberfive = numbers.get(4);
        this.numbersix = numbers.get(5);
        this.numberseven = numbers.get(6);
        this.numbereight = numbers.get(7);
        this.numbernine = numbers.get(8);
        this.numberten = numbers.get(9);
        this.numbereleven = numbers.get(10);
        this.numbertwelve = numbers.get(11);
        this.numberthirteen = numbers.get(12);
        this.numberfourteen = numbers.get(13);
        this.numberfivteen = numbers.get(14);
    }    
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    public int getNumberone() {
        return this.numberone;
    }
    
    public void setNumberone(int numberone) {
        this.numberone = numberone;
    }
    
    public int getNumbertwo() {
        return this.numbertwo;
    }
    
    public void setNumbertwo(int numbertwo) {
        this.numbertwo = numbertwo;
    }
    
    public int getNumberthree() {
        return this.numberthree;
    }
    
    public void setNumberthree(int numberthree) {
        this.numberthree = numberthree;
    }
    
    public int getNumberfour() {
        return this.numberfour;
    }
    
    public void setNumberfour(int numberfour) {
        this.numberfour = numberfour;
    }

    
    public int getNumberfive() {
        return this.numberfive;
    }
    
    public void setNumberfive(int numberfive) {
        this.numberfive = numberfive;
    }

    
    public int getNumbersix() {
        return this.numbersix;
    }
    
    public void setNumbersix(int numbersix) {
        this.numbersix = numbersix;
    }
    
    
    public int getNumberseven() {
        return this.numberseven;
    }
    
    public void setNumberseven(int numberseven) {
        this.numberseven = numberseven;
    }
    
    public int getNumbereight() {
        return this.numbereight;
    }
    
    public void setNumbereight(int numbeeight) {
        this.numbereight = numbereight;
    }
    
    
    public int getNumbernine() {
        return this.numbernine;
    }
    
    public void setNumbernine(int numbernine) {
        this.numbernine = numbernine;
    }
    
    public int getNumberten() {
        return this.numberten;
    }
    
    public void setNumberten(int numberten) {
        this.numberten = numberten;
    }
    
    public int getNumbereleven() {
        return this.numbereleven;
    }
    
    public void setNumbereleven(int numberten) {
        this.numbereleven = numbereleven;
    }
    
    public int getNumbertwelve() {
        return this.numbertwelve;
    }
    
    public void setNumbertwelve(int numbertwelve) {
        this.numbertwelve = numbertwelve;
    }
    
    public int getNumberthirteen() {
        return this.numberthirteen;
    }
    
    public void setNumbernumberthirteen(int numberthirteen) {
        this.numberthirteen = numberthirteen;
    }
    
    public int getNumberfourteen() {
        return this.numberfourteen;
    }
    
    public void setNumbernumberfourteen(int numberfourteen) {
        this.numberfourteen = numberfourteen;
    }
    
    public int getNumberfivteen() {
        return this.numberfivteen;
    }
    
    public void setNumbernumberFourteen(int numberfivteen) {
        this.numberfivteen = numberfivteen;
    }

    
    public Integer getLotteryid() {
        return this.lotteryid;
    }
    
    public void setLotteryid(Integer lotteryid) {
        this.lotteryid = lotteryid;
     }
}


